# Generated by Django 3.2.13 on 2022-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('data_type', models.CharField(max_length=120)),
                ('minimum', models.IntegerField(blank=True)),
                ('maximum', models.IntegerField(blank=True)),
            ],
        ),
    ]
