# Generated by Django 3.2.13 on 2022-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)')], default=',', max_length=10),
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote (")'), ('*', 'Asterisk (*)')], default='"', max_length=10),
        ),
    ]
