# Generated by Django 3.2.13 on 2022-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20220602_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='has_editable_range',
            field=models.BooleanField(default=False),
        ),
    ]
