# Generated by Django 3.2.13 on 2022-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='url',
        ),
        migrations.AddField(
            model_name='dataset',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/'),
        ),
    ]
