# Generated by Django 3.2.13 on 2022-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_auto_20220605_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='order',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
